### ISSUE TITLE
Errors on list of objects

### ISSUE THREAD

**Issue by evan108108** [akka-js/shocon#44]
When I try to parse a list of objects I get this error:

```bash
[error] java.lang.Error: "]":4:5 ..."{\n      id"
[error] at org.akkajs.shocon.package$Config$.apply(SHocon.scala:61)
[error] at org.akkajs.ConfigMacroLoader$.parse(ConfigMacroLoader.scala:88)
```

example:
```
{
  dataSource  = "weather-underground"
  normalizers = [
    {
      id              = "weather-underground_hourly_weather_forcast_retrieved_1"
      streamName      = "hourly_weather_forcast_retrieved"
      outputEventType = "hourly_weather_forcast_retrieved"
      versions        = ["0.1"]
      dir             = "0.1"
      trait           = "RawMessageNormalizerStreamService"
    },
    {
      id              = "my-data-source_2"
      streamName      = "data_retrieved"
      outputEventType = "data_retrieved"
      versions        = ["0.1"]
      dir             = "0.1"
      trait           = "RawMessageNormalizerStreamService"
    },
  ]
}
```

**Comment by andreaTP** [comment]
ok, I'll try to have a look, thanks for reporting!
